import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ToggleSwitch from "@/components/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>デザインシステム</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <ToggleSwitch></ToggleSwitch>
          <h2>Speckleのデモ⏬⏬⏬⏬⏬</h2>
          <iframe
            src="https://speckle.xyz/embed?stream=c11aca7643&commit=03722637ca&c=%5B32.23696%2C-25.44042%2C14.19548%2C-0.81262%2C-0.49831%2C9.18918%2C0%2C1%5D"
            width="1280"
            height="720"
          ></iframe>
        </div>
      </main>
    </>
  );
}
